[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "jpype1>=1.5.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "psycopg2-binary>=2.9.10",
    "pypdf2>=3.0.1",
    "tabula-py>=2.10.0",
    "tomli>=2.2.1",
    "trafilatura>=2.0.0",
    "twilio>=9.4.5",
    "werkzeug>=3.1.3",
]
